"""add_missing_tables_and_indexes_oct_2025

Revision ID: 7cdcb95ba41a
Revises: e4ac51feaebe
Create Date: 2025-10-02 18:32:32.835123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cdcb95ba41a'
down_revision: Union[str, Sequence[str], None] = 'e4ac51feaebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
