"""sync_all_pending_schema_changes

Revision ID: e4ac51feaebe
Revises: 0b1c2d3e4f56
Create Date: 2025-09-30 21:49:04.069127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ac51feaebe'
down_revision: Union[str, Sequence[str], None] = '0b1c2d3e4f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('base_prompt', sa.Text(), nullable=False),
    sa.Column('num_requested', sa.Integer(), nullable=False),
    sa.Column('num_generated', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('generated_sequences', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_generations_batch_id'), 'batch_generations', ['batch_id'], unique=True)
    op.create_index(op.f('ix_batch_generations_id'), 'batch_generations', ['id'], unique=False)
    op.create_table('claim_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.String(length=64), nullable=True),
    sa.Column('paper_title', sa.String(length=500), nullable=True),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_hash', sa.String(length=64), nullable=True),
    sa.Column('claim_type', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('source_section', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('claim_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_records_claim_hash'), 'claim_records', ['claim_hash'], unique=False)
    op.create_index(op.f('ix_claim_records_claim_type'), 'claim_records', ['claim_type'], unique=False)
    op.create_index(op.f('ix_claim_records_confidence_score'), 'claim_records', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_claim_records_created_at'), 'claim_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_claim_records_extraction_method'), 'claim_records', ['extraction_method'], unique=False)
    op.create_index(op.f('ix_claim_records_id'), 'claim_records', ['id'], unique=False)
    op.create_index(op.f('ix_claim_records_paper_id'), 'claim_records', ['paper_id'], unique=False)
    op.create_table('decision_ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('chosen', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_ledger_entries_created_at'), 'decision_ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_ledger_entries_decision_type'), 'decision_ledger_entries', ['decision_type'], unique=False)
    op.create_index(op.f('ix_decision_ledger_entries_id'), 'decision_ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_decision_ledger_entries_subject_id'), 'decision_ledger_entries', ['subject_id'], unique=False)
    op.create_table('evaluation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=64), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('normalized', sa.JSON(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('formula_version', sa.String(length=10), nullable=False),
    sa.Column('formula_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_records_composite_score'), 'evaluation_records', ['composite_score'], unique=False)
    op.create_index(op.f('ix_evaluation_records_created_at'), 'evaluation_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluation_records_formula_hash'), 'evaluation_records', ['formula_hash'], unique=False)
    op.create_index(op.f('ix_evaluation_records_formula_version'), 'evaluation_records', ['formula_version'], unique=False)
    op.create_index(op.f('ix_evaluation_records_hypothesis_id'), 'evaluation_records', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_evaluation_records_id'), 'evaluation_records', ['id'], unique=False)
    op.create_table('experiment_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_uuid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_reference', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exp_jobs_next_run', 'experiment_jobs', ['next_run_at'], unique=False)
    op.create_index('ix_exp_jobs_state_priority', 'experiment_jobs', ['state', 'priority'], unique=False)
    op.create_index(op.f('ix_experiment_jobs_id'), 'experiment_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_experiment_jobs_job_uuid'), 'experiment_jobs', ['job_uuid'], unique=True)
    op.create_index(op.f('ix_experiment_jobs_next_run_at'), 'experiment_jobs', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_experiment_jobs_state'), 'experiment_jobs', ['state'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_uuid', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('refinement_count', sa.Integer(), nullable=True),
    sa.Column('linked_workflow_id', sa.String(length=64), nullable=True),
    sa.Column('linked_experiment_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_domain'), 'hypotheses', ['domain'], unique=False)
    op.create_index(op.f('ix_hypotheses_hypothesis_uuid'), 'hypotheses', ['hypothesis_uuid'], unique=True)
    op.create_index(op.f('ix_hypotheses_id'), 'hypotheses', ['id'], unique=False)
    op.create_index(op.f('ix_hypotheses_linked_experiment_id'), 'hypotheses', ['linked_experiment_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_linked_workflow_id'), 'hypotheses', ['linked_workflow_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False)
    op.create_table('hypothesis_plausibility_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_uuid', sa.String(length=64), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('duplication_penalty', sa.Float(), nullable=False),
    sa.Column('domain_weight', sa.Float(), nullable=True),
    sa.Column('evidence_adjustment', sa.Float(), nullable=True),
    sa.Column('model_score', sa.Float(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_plausibility_metrics_hypothesis_uuid'), 'hypothesis_plausibility_metrics', ['hypothesis_uuid'], unique=False)
    op.create_index(op.f('ix_hypothesis_plausibility_metrics_id'), 'hypothesis_plausibility_metrics', ['id'], unique=False)
    op.create_index('ix_pl_metric_hyp_created', 'hypothesis_plausibility_metrics', ['hypothesis_uuid', 'created_at'], unique=False)
    op.create_table('paper_quality_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.String(length=64), nullable=True),
    sa.Column('paper_title', sa.String(length=500), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('claims_summary', sa.JSON(), nullable=True),
    sa.Column('coverage_ratio', sa.Float(), nullable=True),
    sa.Column('ranking_score', sa.Float(), nullable=True),
    sa.Column('red_flags', sa.JSON(), nullable=True),
    sa.Column('embeddings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_quality_metrics_coverage_ratio'), 'paper_quality_metrics', ['coverage_ratio'], unique=False)
    op.create_index(op.f('ix_paper_quality_metrics_created_at'), 'paper_quality_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_quality_metrics_id'), 'paper_quality_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_paper_quality_metrics_paper_id'), 'paper_quality_metrics', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_quality_metrics_ranking_score'), 'paper_quality_metrics', ['ranking_score'], unique=False)
    op.create_table('peer_review_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.String(length=64), nullable=True),
    sa.Column('paper_title', sa.String(length=500), nullable=True),
    sa.Column('role_reviews', sa.JSON(), nullable=True),
    sa.Column('consensus_score', sa.Float(), nullable=True),
    sa.Column('methodology_score', sa.Float(), nullable=True),
    sa.Column('statistical_score', sa.Float(), nullable=True),
    sa.Column('robustness_score', sa.Float(), nullable=True),
    sa.Column('domain_score', sa.Float(), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_review_records_consensus_score'), 'peer_review_records', ['consensus_score'], unique=False)
    op.create_index(op.f('ix_peer_review_records_created_at'), 'peer_review_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_peer_review_records_id'), 'peer_review_records', ['id'], unique=False)
    op.create_index(op.f('ix_peer_review_records_paper_id'), 'peer_review_records', ['paper_id'], unique=False)
    op.create_index(op.f('ix_peer_review_records_version'), 'peer_review_records', ['version'], unique=False)
    op.create_table('protein_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('generation_method', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('perplexity_score', sa.Float(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=True),
    sa.Column('isoelectric_point', sa.Float(), nullable=True),
    sa.Column('instability_index', sa.Float(), nullable=True),
    sa.Column('hydrophobicity_score', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protein_sequences_generation_id'), 'protein_sequences', ['generation_id'], unique=True)
    op.create_index(op.f('ix_protein_sequences_id'), 'protein_sequences', ['id'], unique=False)
    op.create_table('protgpt2_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('input_length', sa.Integer(), nullable=True),
    sa.Column('output_length', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('perplexity_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protgpt2_metrics_id'), 'protgpt2_metrics', ['id'], unique=False)
    op.create_table('batch_sequence_association',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_generations.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['protein_sequences.id'], ),
    sa.PrimaryKeyConstraint('batch_id', 'sequence_id')
    )
    op.create_table('claim_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=64), nullable=True),
    sa.Column('relation_type', sa.String(length=20), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_relations_claim_id'), 'claim_relations', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_relations_created_at'), 'claim_relations', ['created_at'], unique=False)
    op.create_index(op.f('ix_claim_relations_hypothesis_id'), 'claim_relations', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_claim_relations_id'), 'claim_relations', ['id'], unique=False)
    op.create_index(op.f('ix_claim_relations_relation_type'), 'claim_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_claim_relations_strength'), 'claim_relations', ['strength'], unique=False)
    op.create_table('domain_insertions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('base_sequence', sa.Text(), nullable=False),
    sa.Column('modified_sequence', sa.Text(), nullable=False),
    sa.Column('inserted_domain', sa.Text(), nullable=False),
    sa.Column('domain_function', sa.String(length=100), nullable=True),
    sa.Column('insertion_position', sa.Integer(), nullable=True),
    sa.Column('structural_compatibility', sa.Float(), nullable=True),
    sa.Column('functional_prediction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['protein_sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_insertions_id'), 'domain_insertions', ['id'], unique=False)
    op.create_table('hypothesis_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('support_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_evidences_hypothesis_id'), 'hypothesis_evidences', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_evidences_id'), 'hypothesis_evidences', ['id'], unique=False)
    op.create_table('hypothesis_refinements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('confidence_delta', sa.Float(), nullable=True),
    sa.Column('manual', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_refinements_hypothesis_id'), 'hypothesis_refinements', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_refinements_id'), 'hypothesis_refinements', ['id'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('concept_type', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('embeddings', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source_papers', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('validation_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_concept_type'), 'knowledge_nodes', ['concept_type'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_confidence_score'), 'knowledge_nodes', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_domain'), 'knowledge_nodes', ['domain'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_id'), 'knowledge_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_is_validated'), 'knowledge_nodes', ['is_validated'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_name'), 'knowledge_nodes', ['name'], unique=False)
    op.create_table('protein_optimizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('original_sequence', sa.Text(), nullable=False),
    sa.Column('optimized_sequence', sa.Text(), nullable=False),
    sa.Column('target_property', sa.String(length=100), nullable=False),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('mutations_json', sa.JSON(), nullable=True),
    sa.Column('mutation_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['protein_sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protein_optimizations_id'), 'protein_optimizations', ['id'], unique=False)
    op.create_table('protein_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False),
    sa.Column('property_value', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['protein_sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protein_properties_id'), 'protein_properties', ['id'], unique=False)
    op.create_table('scientific_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alternative_names', sa.JSON(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('mathematical_formulation', sa.Text(), nullable=True),
    sa.Column('domain_primary', sa.String(length=100), nullable=False),
    sa.Column('domains_secondary', sa.JSON(), nullable=True),
    sa.Column('complexity_level', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('applications', sa.JSON(), nullable=True),
    sa.Column('related_methods', sa.JSON(), nullable=True),
    sa.Column('key_papers', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peer_review_status', sa.String(length=20), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scientific_concepts_complexity_level'), 'scientific_concepts', ['complexity_level'], unique=False)
    op.create_index(op.f('ix_scientific_concepts_domain_primary'), 'scientific_concepts', ['domain_primary'], unique=False)
    op.create_index(op.f('ix_scientific_concepts_id'), 'scientific_concepts', ['id'], unique=False)
    op.create_index(op.f('ix_scientific_concepts_name'), 'scientific_concepts', ['name'], unique=False)
    op.create_index(op.f('ix_scientific_concepts_peer_review_status'), 'scientific_concepts', ['peer_review_status'], unique=False)
    op.create_table('cross_domain_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('target_domain', sa.String(length=100), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('target_concept_name', sa.String(length=255), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('mapping_rationale', sa.Text(), nullable=True),
    sa.Column('evidence_strength', sa.String(length=20), nullable=True),
    sa.Column('use_cases', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_count', sa.Integer(), nullable=True),
    sa.Column('dispute_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['scientific_concepts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_domain_mappings_concept_id'), 'cross_domain_mappings', ['concept_id'], unique=False)
    op.create_index(op.f('ix_cross_domain_mappings_evidence_strength'), 'cross_domain_mappings', ['evidence_strength'], unique=False)
    op.create_index(op.f('ix_cross_domain_mappings_id'), 'cross_domain_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_cross_domain_mappings_mapping_type'), 'cross_domain_mappings', ['mapping_type'], unique=False)
    op.create_index(op.f('ix_cross_domain_mappings_similarity_score'), 'cross_domain_mappings', ['similarity_score'], unique=False)
    op.create_index(op.f('ix_cross_domain_mappings_target_domain'), 'cross_domain_mappings', ['target_domain'], unique=False)
    op.create_table('knowledge_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('predicate', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('evidence_papers', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_relations_id'), 'knowledge_relations', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_relations_object_id'), 'knowledge_relations', ['object_id'], unique=False)
    op.create_index(op.f('ix_knowledge_relations_predicate'), 'knowledge_relations', ['predicate'], unique=False)
    op.create_index(op.f('ix_knowledge_relations_strength'), 'knowledge_relations', ['strength'], unique=False)
    op.create_index(op.f('ix_knowledge_relations_subject_id'), 'knowledge_relations', ['subject_id'], unique=False)
    op.create_index(op.f('ix_knowledge_relations_validation_status'), 'knowledge_relations', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_relations_validation_status'), table_name='knowledge_relations')
    op.drop_index(op.f('ix_knowledge_relations_subject_id'), table_name='knowledge_relations')
    op.drop_index(op.f('ix_knowledge_relations_strength'), table_name='knowledge_relations')
    op.drop_index(op.f('ix_knowledge_relations_predicate'), table_name='knowledge_relations')
    op.drop_index(op.f('ix_knowledge_relations_object_id'), table_name='knowledge_relations')
    op.drop_index(op.f('ix_knowledge_relations_id'), table_name='knowledge_relations')
    op.drop_table('knowledge_relations')
    op.drop_index(op.f('ix_cross_domain_mappings_target_domain'), table_name='cross_domain_mappings')
    op.drop_index(op.f('ix_cross_domain_mappings_similarity_score'), table_name='cross_domain_mappings')
    op.drop_index(op.f('ix_cross_domain_mappings_mapping_type'), table_name='cross_domain_mappings')
    op.drop_index(op.f('ix_cross_domain_mappings_id'), table_name='cross_domain_mappings')
    op.drop_index(op.f('ix_cross_domain_mappings_evidence_strength'), table_name='cross_domain_mappings')
    op.drop_index(op.f('ix_cross_domain_mappings_concept_id'), table_name='cross_domain_mappings')
    op.drop_table('cross_domain_mappings')
    op.drop_index(op.f('ix_scientific_concepts_peer_review_status'), table_name='scientific_concepts')
    op.drop_index(op.f('ix_scientific_concepts_name'), table_name='scientific_concepts')
    op.drop_index(op.f('ix_scientific_concepts_id'), table_name='scientific_concepts')
    op.drop_index(op.f('ix_scientific_concepts_domain_primary'), table_name='scientific_concepts')
    op.drop_index(op.f('ix_scientific_concepts_complexity_level'), table_name='scientific_concepts')
    op.drop_table('scientific_concepts')
    op.drop_index(op.f('ix_protein_properties_id'), table_name='protein_properties')
    op.drop_table('protein_properties')
    op.drop_index(op.f('ix_protein_optimizations_id'), table_name='protein_optimizations')
    op.drop_table('protein_optimizations')
    op.drop_index(op.f('ix_knowledge_nodes_name'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_is_validated'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_domain'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_confidence_score'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_concept_type'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_hypothesis_refinements_id'), table_name='hypothesis_refinements')
    op.drop_index(op.f('ix_hypothesis_refinements_hypothesis_id'), table_name='hypothesis_refinements')
    op.drop_table('hypothesis_refinements')
    op.drop_index(op.f('ix_hypothesis_evidences_id'), table_name='hypothesis_evidences')
    op.drop_index(op.f('ix_hypothesis_evidences_hypothesis_id'), table_name='hypothesis_evidences')
    op.drop_table('hypothesis_evidences')
    op.drop_index(op.f('ix_domain_insertions_id'), table_name='domain_insertions')
    op.drop_table('domain_insertions')
    op.drop_index(op.f('ix_claim_relations_strength'), table_name='claim_relations')
    op.drop_index(op.f('ix_claim_relations_relation_type'), table_name='claim_relations')
    op.drop_index(op.f('ix_claim_relations_id'), table_name='claim_relations')
    op.drop_index(op.f('ix_claim_relations_hypothesis_id'), table_name='claim_relations')
    op.drop_index(op.f('ix_claim_relations_created_at'), table_name='claim_relations')
    op.drop_index(op.f('ix_claim_relations_claim_id'), table_name='claim_relations')
    op.drop_table('claim_relations')
    op.drop_table('batch_sequence_association')
    op.drop_index(op.f('ix_protgpt2_metrics_id'), table_name='protgpt2_metrics')
    op.drop_table('protgpt2_metrics')
    op.drop_index(op.f('ix_protein_sequences_id'), table_name='protein_sequences')
    op.drop_index(op.f('ix_protein_sequences_generation_id'), table_name='protein_sequences')
    op.drop_table('protein_sequences')
    op.drop_index(op.f('ix_peer_review_records_version'), table_name='peer_review_records')
    op.drop_index(op.f('ix_peer_review_records_paper_id'), table_name='peer_review_records')
    op.drop_index(op.f('ix_peer_review_records_id'), table_name='peer_review_records')
    op.drop_index(op.f('ix_peer_review_records_created_at'), table_name='peer_review_records')
    op.drop_index(op.f('ix_peer_review_records_consensus_score'), table_name='peer_review_records')
    op.drop_table('peer_review_records')
    op.drop_index(op.f('ix_paper_quality_metrics_ranking_score'), table_name='paper_quality_metrics')
    op.drop_index(op.f('ix_paper_quality_metrics_paper_id'), table_name='paper_quality_metrics')
    op.drop_index(op.f('ix_paper_quality_metrics_id'), table_name='paper_quality_metrics')
    op.drop_index(op.f('ix_paper_quality_metrics_created_at'), table_name='paper_quality_metrics')
    op.drop_index(op.f('ix_paper_quality_metrics_coverage_ratio'), table_name='paper_quality_metrics')
    op.drop_table('paper_quality_metrics')
    op.drop_index('ix_pl_metric_hyp_created', table_name='hypothesis_plausibility_metrics')
    op.drop_index(op.f('ix_hypothesis_plausibility_metrics_id'), table_name='hypothesis_plausibility_metrics')
    op.drop_index(op.f('ix_hypothesis_plausibility_metrics_hypothesis_uuid'), table_name='hypothesis_plausibility_metrics')
    op.drop_table('hypothesis_plausibility_metrics')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_linked_workflow_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_linked_experiment_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_hypothesis_uuid'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_domain'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_experiment_jobs_state'), table_name='experiment_jobs')
    op.drop_index(op.f('ix_experiment_jobs_next_run_at'), table_name='experiment_jobs')
    op.drop_index(op.f('ix_experiment_jobs_job_uuid'), table_name='experiment_jobs')
    op.drop_index(op.f('ix_experiment_jobs_id'), table_name='experiment_jobs')
    op.drop_index('ix_exp_jobs_state_priority', table_name='experiment_jobs')
    op.drop_index('ix_exp_jobs_next_run', table_name='experiment_jobs')
    op.drop_table('experiment_jobs')
    op.drop_index(op.f('ix_evaluation_records_id'), table_name='evaluation_records')
    op.drop_index(op.f('ix_evaluation_records_hypothesis_id'), table_name='evaluation_records')
    op.drop_index(op.f('ix_evaluation_records_formula_version'), table_name='evaluation_records')
    op.drop_index(op.f('ix_evaluation_records_formula_hash'), table_name='evaluation_records')
    op.drop_index(op.f('ix_evaluation_records_created_at'), table_name='evaluation_records')
    op.drop_index(op.f('ix_evaluation_records_composite_score'), table_name='evaluation_records')
    op.drop_table('evaluation_records')
    op.drop_index(op.f('ix_decision_ledger_entries_subject_id'), table_name='decision_ledger_entries')
    op.drop_index(op.f('ix_decision_ledger_entries_id'), table_name='decision_ledger_entries')
    op.drop_index(op.f('ix_decision_ledger_entries_decision_type'), table_name='decision_ledger_entries')
    op.drop_index(op.f('ix_decision_ledger_entries_created_at'), table_name='decision_ledger_entries')
    op.drop_table('decision_ledger_entries')
    op.drop_index(op.f('ix_claim_records_paper_id'), table_name='claim_records')
    op.drop_index(op.f('ix_claim_records_id'), table_name='claim_records')
    op.drop_index(op.f('ix_claim_records_extraction_method'), table_name='claim_records')
    op.drop_index(op.f('ix_claim_records_created_at'), table_name='claim_records')
    op.drop_index(op.f('ix_claim_records_confidence_score'), table_name='claim_records')
    op.drop_index(op.f('ix_claim_records_claim_type'), table_name='claim_records')
    op.drop_index(op.f('ix_claim_records_claim_hash'), table_name='claim_records')
    op.drop_table('claim_records')
    op.drop_index(op.f('ix_batch_generations_id'), table_name='batch_generations')
    op.drop_index(op.f('ix_batch_generations_batch_id'), table_name='batch_generations')
    op.drop_table('batch_generations')
    # ### end Alembic commands ###
