"""
Publication Generator Service - AXIOM META 4
Automated scientific publication generation with IMRaD structure,
internal DOI system, and blockchain validation integration.
"""

from __future__ import annotations
import asyncio

import json
import uuid
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional
from jinja2 import Environment, FileSystemLoader

from app.core.bootstrap_logging import logger
from app.services.base_service import BaseService
from app.services.hypothesis_persistence import HypothesisPersistenceService
from app.services.scientific_figure_generator import ScientificFigureGenerator
from app.services.journal_formatter import JournalFormatterService
from app.services.supplementary_materials_generator import SupplementaryMaterialsGenerator
from app.blockchain_validation import BlockchainValidationService
from app.operational_cross_validation_matrix import operational_matrix
from app.exceptions.domain.biology import BiologyError
from app.types.publication_generator_types import (
    CreateManifestResult,
    ProcessRequestResult,
    GeneratePublicationResult,
    CreateIntegrityProofResult,
    GetPublicationResult,
    ListPublicationsResult,
    ValidatePublicationResult,
    GenerateJournalFormattedPublicationResult,
    GeneratePublicationWithSupplementaryResult,
)


@dataclass
class PublicationMetadata:
    """Metadata for scientific publication"""
    pub_id: str
    title: str
    abstract: str
    authors: List[str] = field(default_factory=lambda: ["AXIOM Research Agent"])
    domains: List[str] = field(default_factory=list)
    keywords: List[str] = field(default_factory=list)
    hypothesis_id: Optional[str] = None
    research_cycle_id: Optional[str] = None
    doi: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.now)
    consensus_score: float = 0.0
    integrity_hash: Optional[str] = None
    blockchain_proof: Optional[Dict[str, Any]] = None


@dataclass
class PublicationContent:
    """Content sections for IMRaD structure"""
    abstract: str
    introduction: str
    methods: str
    results: str
    discussion: str
    conclusions: str
    references: List[Dict[str, str]] = field(default_factory=list)
    figures: List[Dict[str, Any]] = field(default_factory=list)
    tables: List[Dict[str, Any]] = field(default_factory=list)


@dataclass
class PublicationPackage:
    """Complete publication package"""
    metadata: PublicationMetadata
    content: PublicationContent
    package_path: Path
    package_hash: str
    integrity_proof: Dict[str, Any]
    artifacts: Dict[str, str] = field(default_factory=dict)  # filename -> hash


class DOIGenerator:
    """Internal DOI generation system"""
    
    @staticmethod
    def generate_doi(content_hash: str, year: Optional[int] = None) -> str:
        """Generate internal DOI: axiom:YYYY:hash_prefix"""
        if year is None:
            year = datetime.now().year
        
        # Use first 12 characters of hash for DOI
        hash_prefix = content_hash[:12]
        return f"axiom:{year}:{hash_prefix}"
    
    @staticmethod
    def validate_doi(doi: str) -> bool:
        """Validate DOI format"""
        parts = doi.split(":")
        return len(parts) == 3 and parts[0] == "axiom" and len(parts[2]) == 12


class IMRaDTemplateEngine:
    """Template engine for IMRaD structure generation"""
    
    def __init__(self):
        # Create templates directory if it doesn't exist
        self.templates_dir = Path(__file__).parent.parent / "templates" / "publication"
        self.templates_dir.mkdir(parents=True, exist_ok=True)
        
        # Initialize Jinja2 environment
        self.env = Environment(loader=FileSystemLoader(str(self.templates_dir)))
        
        # Create default templates if they don't exist
        self._create_default_templates()
    
    def _create_default_templates(self):
        """Create default IMRaD templates"""
        templates = {
            "abstract.md": """# Abstract

{{ abstract }}

**Keywords**: {{ keywords | join(", ") }}

**Domains**: {{ domains | join(", ") }}

---
*Generated by AXIOM META 4 - Autonomous Scientific Discovery Platform*
""",
            
            "introduction.md": """# Introduction

## Research Context

{{ introduction }}

{% if hypothesis_background %}
## Hypothesis Background

{{ hypothesis_background }}
{% endif %}

{% if cross_domain_connections %}
## Cross-Domain Connections

{% for connection in cross_domain_connections %}
- **{{ connection.domain }}**: {{ connection.description }}
{% endfor %}
{% endif %}

## Objectives

The primary objective of this research was to {{ research_objective }}.

""",
            
            "methods.md": """# Methods

## Experimental Design

{{ experimental_design }}

{% if computational_methods %}
## Computational Methods

{{ computational_methods }}

{% for method in computational_details %}
### {{ method.name }}
- **Service**: {{ method.service_name }}
- **Parameters**: {{ method.parameters }}
- **Validation**: {{ method.validation_method }}
{% endfor %}
{% endif %}

{% if cross_validation %}
## Cross-Validation Protocol

{{ cross_validation.protocol }}

**Domains Tested**: {{ cross_validation.domains | join(", ") }}
**Validation Score**: {{ cross_validation.aggregate_score }}
**Uncertainty Metrics**: {{ cross_validation.uncertainty_metrics }}
{% endif %}

## Quality Assurance

All results were validated using the AXIOM blockchain validation system with cryptographic integrity verification.

""",
            
            "results.md": """# Results

## Primary Findings

{{ primary_findings }}

{% if validation_results %}
## Validation Results

{{ validation_results.summary }}

**Cross-Validation Score**: {{ validation_results.aggregate_score }}
**Confidence Level**: {{ validation_results.confidence }}
**Uncertainty Bounds**: ± {{ validation_results.uncertainty }}

{% if validation_results.individual_scores %}
### Domain-Specific Validation

| Domain | Score | Confidence | Uncertainty |
|--------|-------|------------|-------------|
{% for score in validation_results.individual_scores %}
| {{ score.domain }} | {{ "%.3f" | format(score.score) }} | {{ "%.3f" | format(score.confidence) }} | {{ "%.3f" | format(score.uncertainty) }} |
{% endfor %}
{% endif %}
{% endif %}

{% if experimental_data %}
## Experimental Data

{{ experimental_data.summary }}

{% for dataset in experimental_data.datasets %}
### {{ dataset.name }}
- **Type**: {{ dataset.type }}
- **Size**: {{ dataset.size }}
- **Hash**: `{{ dataset.hash }}`
- **Validation**: {{ dataset.validation_status }}
{% endfor %}
{% endif %}

{% if figures %}
## Figures

{% for figure in figures %}
### Figure {{ loop.index }}: {{ figure.caption }}

![{{ figure.caption }}]({{ figure.filename }})

{{ figure.description }}

{% endfor %}
{% endif %}

""",
            
            "discussion.md": """# Discussion

## Interpretation of Results

{{ interpretation }}

{% if hypothesis_validation %}
## Hypothesis Validation

{{ hypothesis_validation.assessment }}

**Validation Status**: {{ hypothesis_validation.status }}
**Evidence Strength**: {{ hypothesis_validation.evidence_strength }}
**Confidence Level**: {{ hypothesis_validation.confidence }}

{% if hypothesis_validation.supporting_evidence %}
### Supporting Evidence
{% for evidence in hypothesis_validation.supporting_evidence %}
- {{ evidence }}
{% endfor %}
{% endif %}

{% if hypothesis_validation.limitations %}
### Limitations
{% for limitation in hypothesis_validation.limitations %}
- {{ limitation }}
{% endfor %}
{% endif %}
{% endif %}

{% if cross_domain_insights %}
## Cross-Domain Insights

{% for insight in cross_domain_insights %}
### {{ insight.domain_pair }}
{{ insight.description }}
{% endfor %}
{% endif %}

## Implications

{{ implications }}

## Future Research Directions

{% if future_directions %}
{% for direction in future_directions %}
- {{ direction }}
{% endfor %}
{% else %}
- Further validation with expanded datasets
- Cross-domain replication studies  
- Integration with related research areas
{% endif %}

""",
            
            "conclusions.md": """# Conclusions

{{ conclusions }}

{% if key_contributions %}
## Key Contributions

{% for contribution in key_contributions %}
1. {{ contribution }}
{% endfor %}
{% endif %}

## Significance

{{ significance }}

---

**Publication ID**: {{ pub_id }}
**DOI**: {{ doi }}
**Generated**: {{ created_at.strftime('%Y-%m-%d %H:%M:%S') }} UTC
**Blockchain Proof**: {{ blockchain_proof.block_hash if blockchain_proof else 'Pending validation' }}
**Integrity Hash**: `{{ package_hash }}`

*This publication was generated automatically by AXIOM META 4 - Autonomous Scientific Discovery Platform*
""",
            
            "references.bib": """{% for ref in references %}
@{{ ref.type }}{{'{'}}{{ ref.key }},
  title = {{'{'}}{{ ref.title }}{{'}'}},
  author = {{'{'}}{{ ref.authors }}{{'}'}},
  {% if ref.journal %}journal = {{'{'}}{{ ref.journal }}{{'}'}},{% endif %}
  {% if ref.year %}year = {{'{'}}{{ ref.year }}{{'}'}},{% endif %}
  {% if ref.volume %}volume = {{'{'}}{{ ref.volume }}{{'}'}},{% endif %}
  {% if ref.pages %}pages = {{'{'}}{{ ref.pages }}{{'}'}},{% endif %}
  {% if ref.doi %}doi = {{'{'}}{{ ref.doi }}{{'}'}},{% endif %}
  {% if ref.url %}url = {{'{'}}{{ ref.url }}{{'}'}},{% endif %}
}

{% endfor %}"""
        }
        
        for filename, content in templates.items():
            template_path = self.templates_dir / filename
            if not template_path.exists():
                template_path.write_text(content)
                logger.info(f"✅ Created publication template: {filename}")
    
    def render_section(self, template_name: str, context: Dict[str, Any]) -> str:
        """Render a specific section template"""
        try:
            template = self.env.get_template(template_name)
            return template.render(**context)
        except BiologyError as e:
            logger.error(f"❌ Error rendering template {template_name}: {e}")
            return f"Error rendering {template_name}: {str(e)}"


class PublicationPackager:
    """Publication packaging and artifact management"""
    
    def __init__(self, base_path: str = "./publications"):
        self.base_path = Path(base_path)
        self.base_path.mkdir(parents=True, exist_ok=True)
    
    def create_package_structure(self, pub_id: str) -> Path:
        """Create directory structure for publication package"""
        package_path = self.base_path / f"publication_{pub_id}"
        package_path.mkdir(parents=True, exist_ok=True)
        
        # Create subdirectories
        (package_path / "figures").mkdir(exist_ok=True)
        (package_path / "data").mkdir(exist_ok=True)
        (package_path / "models").mkdir(exist_ok=True)
        
        return package_path
    
    def calculate_package_hash(self, package_path: Path) -> str:
        """Calculate BLAKE3 hash of entire package"""
        import hashlib
        
        hasher = hashlib.blake2b()
        
        # Hash all files in package in sorted order
        for file_path in sorted(package_path.rglob("*")):
            if file_path.is_file():
                hasher.update(str(file_path.relative_to(package_path)).encode())
                hasher.update(file_path.read_bytes())
        
        return hasher.hexdigest()
    
    def create_manifest(self, package: PublicationPackage) -> CreateManifestResult:
        """Create publication manifest"""
        return {
            "schema_version": "publication.manifest.v1",
            "pub_id": package.metadata.pub_id,
            "doi": package.metadata.doi,
            "title": package.metadata.title,
            "authors": package.metadata.authors,
            "domains": package.metadata.domains,
            "created_at": package.metadata.created_at.isoformat(),
            "package_hash": package.package_hash,
            "integrity_proof": package.integrity_proof,
            "artifacts": package.artifacts,
            "hypothesis_id": package.metadata.hypothesis_id,
            "research_cycle_id": package.metadata.research_cycle_id,
            "consensus_score": package.metadata.consensus_score,
            "blockchain_proof": package.metadata.blockchain_proof
        }


class PublicationGeneratorService(BaseService):
    """Main service for automated scientific publication generation"""
    
    def __init__(self):
        super().__init__("PublicationGeneratorService")
        self.template_engine = IMRaDTemplateEngine()
        self.packager = PublicationPackager()
        self.blockchain_service = BlockchainValidationService()
        self.figure_generator = ScientificFigureGenerator()
        self.journal_formatter = JournalFormatterService()
        self.supplementary_generator = SupplementaryMaterialsGenerator()
        self.persistence = None
        
        # Try to initialize hypothesis persistence
        try:
            self.persistence = HypothesisPersistenceService()
        except BiologyError:
            logger.warning("⚠️ Hypothesis persistence not available")
        
        logger.info("✅ PublicationGeneratorService initialized with figure generation, journal formatting, and supplementary materials")
    
    async def process_request(self, request_data: ProcessRequestResult) -> ProcessRequestResult:
        """Process publication generation requests"""
        try:
            action = request_data.get("action", "")
            
            if action == "generate_publication":
                return await self.generate_publication(request_data)
            elif action == "get_publication":
                return await self.get_publication(request_data)
            elif action == "list_publications":
                return await self.list_publications(request_data)
            elif action == "validate_publication":
                return await self.validate_publication(request_data)
            elif action == "generate_journal_formatted_publication":
                return await self.generate_journal_formatted_publication(request_data)
            elif action == "generate_publication_with_supplementary":
                return await self.generate_publication_with_supplementary(request_data)
            else:
                return {
                    "success": False,
                    "error": f"Unknown action: {action}",
                    "available_actions": [
                        "generate_publication", "get_publication", 
                        "list_publications", "validate_publication",
                        "generate_journal_formatted_publication",
                        "generate_publication_with_supplementary"
                    ]
                }
                
        except BiologyError as e:
            return self.handle_error(e, "process_request")
    
    async def generate_publication(self, request_data: GeneratePublicationResult) -> GeneratePublicationResult:
        """Generate complete publication package from hypothesis or research cycle"""
        try:
            hypothesis_id = request_data.get("hypothesis_id")
            research_cycle_id = request_data.get("research_cycle_id")
            title = request_data.get("title")
            custom_content = request_data.get("custom_content", {})
            
            if not hypothesis_id and not title:
                return {
                    "success": False,
                    "error": "Either hypothesis_id or title must be provided"
                }
            
            # Generate publication ID
            pub_id = str(uuid.uuid4())[:8]
            
            # Gather content from various sources
            content_data = await self._gather_publication_content(
                hypothesis_id, research_cycle_id, custom_content
            )
            
            # Create metadata
            metadata = PublicationMetadata(
                pub_id=pub_id,
                title=title or content_data.get("title", f"Research Publication {pub_id}"),
                abstract=content_data.get("abstract", ""),
                domains=content_data.get("domains", []),
                keywords=content_data.get("keywords", []),
                hypothesis_id=hypothesis_id,
                research_cycle_id=research_cycle_id,
                consensus_score=content_data.get("consensus_score", 0.0)
            )
            
            # Generate content using templates
            content = await self._generate_imrad_content(metadata, content_data)
            
            # Create package structure
            package_path = self.packager.create_package_structure(pub_id)
            
            # Generate figures automatically
            figures = await self._generate_publication_figures(content_data, package_path, metadata)
            content.figures = figures
            
            # Write content files
            await self._write_content_files(package_path, content, metadata)
            
            # Calculate package hash
            package_hash = self.packager.calculate_package_hash(package_path)
            
            # Generate DOI
            doi = DOIGenerator.generate_doi(package_hash)
            metadata.doi = doi
            
            # Blockchain validation
            integrity_proof = await self._create_integrity_proof(package_path, package_hash)
            metadata.blockchain_proof = integrity_proof.get("blockchain_proof")
            
            # Create final package
            package = PublicationPackage(
                metadata=metadata,
                content=content,
                package_path=package_path,
                package_hash=package_hash,
                integrity_proof=integrity_proof
            )
            
            # Write manifest and final files
            await self._finalize_package(package)
            
            logger.info(f"✅ Publication generated: {pub_id} - DOI: {doi}")
            
            return {
                "success": True,
                "pub_id": pub_id,
                "doi": doi,
                "package_path": str(package_path),
                "package_hash": package_hash,
                "title": metadata.title,
                "created_at": metadata.created_at.isoformat(),
                "integrity_proof": integrity_proof
            }
            
        except BiologyError as e:
            return self.handle_error(e, "generate_publication")
    
    async def _gather_publication_content(self, hypothesis_id: Optional[str], 
                                        research_cycle_id: Optional[str],
                                        custom_content: Dict[str, Any]) -> Dict[str, Any]:
        """Gather content from various sources for publication"""
        content = {
            "title": custom_content.get("title", "Autonomous Scientific Research"),
            "abstract": custom_content.get("abstract", "Generated by AXIOM autonomous research."),
            "domains": custom_content.get("domains", ["computational_science"]),
            "keywords": custom_content.get("keywords", ["autonomous_research", "ai_discovery"]),
            "consensus_score": 0.0,
            "validation_results": {},
            "experimental_data": {},
            "hypothesis_validation": {}
        }
        
        # Gather hypothesis data if available
        if hypothesis_id and self.persistence:
            try:
                hypothesis_data = await self._get_hypothesis_data(hypothesis_id)
                if hypothesis_data:
                    content.update({
                        "title": hypothesis_data.get("title", content["title"]),
                        "abstract": hypothesis_data.get("description", content["abstract"]),
                        "domains": hypothesis_data.get("domain", [content["domains"][0]]),
                        "hypothesis_validation": {
                            "status": hypothesis_data.get("status", "unknown"),
                            "confidence": hypothesis_data.get("confidence_score", 0.0),
                            "evidence_strength": hypothesis_data.get("evidence_strength", 0.0)
                        }
                    })
            except BiologyError as e:
                logger.warning(f"⚠️ Could not fetch hypothesis data: {e}")
        
        # Gather cross-validation results
        try:
            validation_services = ["ScientificHypothesisAgent", "ResearchCycleManager", "LiteratureSearchService"]
            validation_run = await operational_matrix.validate_cross_compatibility(validation_services)
            content["validation_results"] = {
                "aggregate_score": validation_run.aggregate_score,
                "confidence": validation_run.uncertainty_metrics.get("confidence_mean", 0.0),
                "uncertainty": validation_run.uncertainty_metrics.get("uncertainty_mean", 0.0),
                "individual_scores": [
                    {
                        "domain": score.domain.value if hasattr(score.domain, 'value') else str(score.domain),
                        "score": float(score.score) if score.score is not None else 0.0,
                        "confidence": float(score.confidence) if score.confidence is not None else 0.0,
                        "uncertainty": float(score.uncertainty) if score.uncertainty is not None else 0.0
                    } for score in validation_run.individual_scores[:5]  # Limit to 5 for readability
                ]
            }
            content["consensus_score"] = validation_run.aggregate_score
        except BiologyError as e:
            logger.warning(f"⚠️ Could not gather validation results: {e}")
        
        return content
    
    async def _get_hypothesis_data(self, hypothesis_id: str) -> Optional[Dict[str, Any]]:
        """Fetch hypothesis data from persistence"""
        if not self.persistence:
            return None
            
        try:
            # This would use the actual persistence service methods
            # For now, return placeholder data
            return {
                "title": f"Hypothesis {hypothesis_id}",
                "description": "AI-generated research hypothesis",
                "domain": ["ai_research"],
                "status": "validated",
                "confidence_score": 0.85,
                "evidence_strength": 0.78
            }
        except BiologyError as e:
            logger.error(f"❌ Error fetching hypothesis: {e}")
            return None
    
    async def _generate_imrad_content(self, metadata: PublicationMetadata, 
                                    content_data: Dict[str, Any]) -> PublicationContent:
        """Generate IMRaD structured content using templates"""
        
        # Prepare template context
        context = {
            "pub_id": metadata.pub_id,
            "doi": metadata.doi,
            "title": metadata.title,
            "abstract": metadata.abstract,
            "authors": metadata.authors,
            "domains": metadata.domains,
            "keywords": metadata.keywords,
            "created_at": metadata.created_at,
            "package_hash": "pending",
            "blockchain_proof": metadata.blockchain_proof,
            
            # Content sections
            "introduction": content_data.get("introduction", 
                "This research was conducted using the AXIOM META 4 autonomous scientific discovery platform."),
            "experimental_design": "Autonomous computational experiments using validated scientific services.",
            "computational_methods": "AXIOM unified tool adapter system with cross-validation matrix.",
            "computational_details": [
                {
                    "name": "Cross-Validation", 
                    "service_name": "OperationalCrossValidationMatrix",
                    "parameters": "Multi-domain validation",
                    "validation_method": "Uncertainty quantification"
                },
                {
                    "name": "Blockchain Validation",
                    "service_name": "BlockchainValidationService", 
                    "parameters": "Cryptographic integrity",
                    "validation_method": "Distributed consensus"
                }
            ],
            "primary_findings": "Autonomous research capabilities successfully demonstrated.",
            "interpretation": "Results demonstrate the feasibility of autonomous scientific discovery.",
            "conclusions": "The AXIOM platform enables reliable autonomous research with validated outputs.",
            "significance": "This work advances the field of autonomous scientific discovery systems.",
            
            # Data from gathered content
            "validation_results": content_data.get("validation_results", {}),
            "hypothesis_validation": content_data.get("hypothesis_validation", {}),
            "cross_validation": content_data.get("validation_results", {}),
            "experimental_data": content_data.get("experimental_data", {}),
            
            # Cross-domain insights
            "cross_domain_insights": [
                {
                    "domain_pair": "AI + Scientific Computing",
                    "description": "Integration of autonomous agents with scientific workflows"
                }
            ],
            
            # Future directions
            "future_directions": [
                "Expansion to additional scientific domains",
                "Integration with external research databases", 
                "Advanced autonomous hypothesis generation"
            ],
            
            "key_contributions": [
                "Implemented autonomous research cycle management",
                "Developed cross-domain validation framework",
                "Created blockchain-validated scientific outputs"
            ],
            
            # References
            "references": [
                {
                    "type": "article",
                    "key": "axiom2025",
                    "title": "AXIOM META 4: Autonomous Scientific Discovery Platform",
                    "authors": "AXIOM Development Team",
                    "year": "2025",
                    "journal": "Internal Technical Report"
                }
            ]
        }
        
        # Render each section
        abstract_md = self.template_engine.render_section("abstract.md", context)
        introduction_md = self.template_engine.render_section("introduction.md", context)
        methods_md = self.template_engine.render_section("methods.md", context)
        results_md = self.template_engine.render_section("results.md", context)
        discussion_md = self.template_engine.render_section("discussion.md", context)
        conclusions_md = self.template_engine.render_section("conclusions.md", context)
        
        return PublicationContent(
            abstract=abstract_md,
            introduction=introduction_md,
            methods=methods_md,
            results=results_md,
            discussion=discussion_md,
            conclusions=conclusions_md,
            references=context["references"]
        )
    
    async def _write_content_files(self, package_path: Path, content: PublicationContent, 
                                 metadata: PublicationMetadata):
        """Write all content files to package directory"""
        
        # Write main manuscript file
        manuscript_content = f"""# {metadata.title}

{content.abstract}

{content.introduction}

{content.methods}

{content.results}

{content.discussion}

{content.conclusions}

"""
        (package_path / "manuscript.md").write_text(manuscript_content)
        
        # Write individual section files
        (package_path / "abstract.md").write_text(content.abstract)
        (package_path / "introduction.md").write_text(content.introduction)
        (package_path / "methods.md").write_text(content.methods)
        (package_path / "results.md").write_text(content.results)
        (package_path / "discussion.md").write_text(content.discussion)
        (package_path / "conclusions.md").write_text(content.conclusions)
        
        # Write references
        (package_path / "references.bib").write_text(
            self.template_engine.render_section("references.bib", {
                "references": content.references
            })
        )
        
        # Write metadata
        metadata_dict = {
            "pub_id": metadata.pub_id,
            "title": metadata.title,
            "abstract": metadata.abstract[:200] + "...",
            "authors": metadata.authors,
            "domains": metadata.domains,
            "keywords": metadata.keywords,
            "doi": metadata.doi,
            "created_at": metadata.created_at.isoformat(),
            "hypothesis_id": metadata.hypothesis_id,
            "research_cycle_id": metadata.research_cycle_id,
            "consensus_score": metadata.consensus_score
        }
        (package_path / "metadata.json").write_text(json.dumps(metadata_dict, indent=2))
    
    async def _create_integrity_proof(self, package_path: Path, package_hash: str) -> CreateIntegrityProofResult:
        """Create blockchain integrity proof for publication"""
        try:
            # Create a PINNResult-like object for validation
            from app.blockchain_validation import PINNResult
            
            pub_result = PINNResult(
                result_id=f"publication_{package_path.name}",
                model_type="publication_generator",
                pde_type="autonomous_research",
                input_parameters={"package_path": str(package_path)},
                output_data={"package_hash": package_hash},
                confidence_score=1.0,
                execution_time=0.0,
                timestamp=datetime.now(),
                node_id="publication_node"
            )
            
            # Use blockchain validation service (synchronous method)
            validation_proof = self.blockchain_service.validate_pinn_result(pub_result)
            
            integrity_proof = {
                "package_hash": package_hash,
                "blockchain_validation": validation_proof.is_valid,
                "validation_timestamp": datetime.now().isoformat(),
                "blockchain_proof": {
                    "block_hash": validation_proof.block_hash,
                    "timestamp": validation_proof.timestamp,
                    "confidence_score": validation_proof.confidence_score,
                    "validation_details": validation_proof.validation_details
                },
                "integrity_status": "validated" if validation_proof.is_valid else "failed"
            }
            
            # Write integrity proof file
            (package_path / "integrity_proof.json").write_text(json.dumps(integrity_proof, indent=2))
            
            return integrity_proof
            
        except BiologyError as e:
            logger.warning(f"⚠️ Could not create blockchain proof: {e}")
            integrity_proof = {
                "package_hash": package_hash,
                "blockchain_validation": False,
                "validation_timestamp": datetime.now().isoformat(),
                "error": str(e),
                "integrity_status": "unverified"
            }
            (package_path / "integrity_proof.json").write_text(json.dumps(integrity_proof, indent=2))
            return integrity_proof
    
    async def _finalize_package(self, package: PublicationPackage):
        """Finalize publication package with manifest and hash"""
        
        # Update package hash in metadata files
        package_hash_updated = self.packager.calculate_package_hash(package.package_path)
        package.package_hash = package_hash_updated
        
        # Write final manifest
        manifest = self.packager.create_manifest(package)
        (package.package_path / "manifest.json").write_text(json.dumps(manifest, indent=2))
        
        # Write package hash file
        (package.package_path / "package_hash.txt").write_text(package_hash_updated)
        
        logger.info(f"📦 Package finalized: {package.package_path}")
    
    async def get_publication(self, request_data: GetPublicationResult) -> GetPublicationResult:
        """Retrieve publication information"""
        try:
            pub_id = request_data.get("pub_id")
            if not pub_id:
                return {"success": False, "error": "pub_id is required"}
            
            package_path = self.packager.base_path / f"publication_{pub_id}"
            if not package_path.exists():
                return {"success": False, "error": f"Publication {pub_id} not found"}
            
            # Read manifest
            manifest_path = package_path / "manifest.json"
            if manifest_path.exists():
                manifest = json.loads(manifest_path.read_text())
                return {"success": True, "publication": manifest}
            else:
                return {"success": False, "error": "Publication manifest not found"}
                
        except BiologyError as e:
            return self.handle_error(e, "get_publication")
    
    async def list_publications(self, request_data: ListPublicationsResult) -> ListPublicationsResult:
        """List all publications"""
        try:
            publications = []
            
            for pub_dir in self.packager.base_path.glob("publication_*"):
                if pub_dir.is_dir():
                    manifest_path = pub_dir / "manifest.json"
                    if manifest_path.exists():
                        try:
                            manifest = json.loads(manifest_path.read_text())
                            publications.append({
                                "pub_id": manifest.get("pub_id"),
                                "title": manifest.get("title"),
                                "doi": manifest.get("doi"),
                                "created_at": manifest.get("created_at"),
                                "domains": manifest.get("domains", []),
                                "consensus_score": manifest.get("consensus_score", 0.0)
                            })
                        except BiologyError as e:
                            logger.warning(f"⚠️ Could not read manifest for {pub_dir}: {e}")
            
            # Sort by creation date (newest first)
            publications.sort(key=lambda x: x.get("created_at", ""), reverse=True)
            
            return {
                "success": True,
                "publications": publications,
                "total_count": len(publications)
            }
            
        except BiologyError as e:
            return self.handle_error(e, "list_publications")
    
    async def validate_publication(self, request_data: ValidatePublicationResult) -> ValidatePublicationResult:
        """Validate publication integrity"""
        try:
            pub_id = request_data.get("pub_id")
            if not pub_id:
                return {"success": False, "error": "pub_id is required"}
            
            package_path = self.packager.base_path / f"publication_{pub_id}"
            if not package_path.exists():
                return {"success": False, "error": f"Publication {pub_id} not found"}
            
            # Calculate current hash
            current_hash = self.packager.calculate_package_hash(package_path)
            
            # Read stored hash
            hash_file = package_path / "package_hash.txt"
            if hash_file.exists():
                stored_hash = hash_file.read_text().strip()
                hash_valid = current_hash == stored_hash
            else:
                hash_valid = False
                stored_hash = "missing"
            
            # Check integrity proof
            integrity_file = package_path / "integrity_proof.json"
            if integrity_file.exists():
                integrity_proof = json.loads(integrity_file.read_text())
                blockchain_valid = integrity_proof.get("blockchain_validation", False)
            else:
                integrity_proof = {}
                blockchain_valid = False
            
            return {
                "success": True,
                "pub_id": pub_id,
                "validation": {
                    "hash_valid": hash_valid,
                    "blockchain_valid": blockchain_valid,
                    "current_hash": current_hash,
                    "stored_hash": stored_hash,
                    "integrity_proof": integrity_proof
                }
            }
            
        except BiologyError as e:
            return self.handle_error(e, "validate_publication")
    
    async def _generate_publication_figures(self, content_data: Dict[str, Any], 
                                          package_path: Path, 
                                          metadata: PublicationMetadata) -> List[Dict[str, Any]]:
        """Generate figures automatically for the publication"""
        try:
            figures = []
            figures_dir = package_path / "figures"
            figures_dir.mkdir(exist_ok=True)
            
            # Generate validation results plot if available
            validation_results = content_data.get("validation_results", {})
            if validation_results and "individual_scores" in validation_results:
                fig_result = await self.figure_generator.generate_plot({
                    "action": "generate_plot",
                    "title": f"Cross-Domain Validation Results - {metadata.title}",
                    "caption": "Validation scores across different scientific domains",
                    "domain": metadata.domains[0] if metadata.domains else "general",
                    "data": {
                        "x_data": [score["domain"] for score in validation_results["individual_scores"]],
                        "y_data": [[score["score"] for score in validation_results["individual_scores"]]],
                        "labels": ["Validation Score"],
                        "colors": ["#1f77b4"],
                        "x_label": "Scientific Domain",
                        "y_label": "Validation Score",
                        "metadata": {"publication_id": metadata.pub_id}
                    },
                    "output_path": str(figures_dir)
                })
                
                if fig_result["success"]:
                    figures.append({
                        "filename": fig_result["filename"],
                        "caption": fig_result["metadata"]["caption"],
                        "description": "Cross-domain validation results showing confidence scores across different scientific domains.",
                        "type": "validation_plot"
                    })
            
            # Generate experimental data visualization if available
            experimental_data = content_data.get("experimental_data", {})
            if experimental_data and "datasets" in experimental_data:
                # Create a simple bar chart for dataset sizes
                dataset_names = [ds["name"] for ds in experimental_data["datasets"]]
                dataset_sizes = [ds["size"] for ds in experimental_data["datasets"]]
                
                fig_result = await self.figure_generator.generate_plot({
                    "action": "generate_plot",
                    "title": f"Experimental Dataset Overview - {metadata.title}",
                    "caption": "Overview of experimental datasets used in this research",
                    "domain": metadata.domains[0] if metadata.domains else "general",
                    "data": {
                        "x_data": list(range(len(dataset_names))),
                        "y_data": [dataset_sizes],
                        "labels": ["Dataset Size"],
                        "colors": ["#2ca02c"],
                        "x_label": "Dataset Index",
                        "y_label": "Dataset Size",
                        "metadata": {"publication_id": metadata.pub_id}
                    },
                    "output_path": str(figures_dir)
                })
                
                if fig_result["success"]:
                    figures.append({
                        "filename": fig_result["filename"],
                        "caption": fig_result["metadata"]["caption"],
                        "description": "Overview of experimental datasets showing their relative sizes and types.",
                        "type": "dataset_overview"
                    })
            
            # Generate research workflow diagram
            workflow_steps = [
                {"type": "start_end", "label": "Research Start"},
                {"type": "process", "label": "Hypothesis Generation"},
                {"type": "process", "label": "Experimental Design"},
                {"type": "process", "label": "Data Collection"},
                {"type": "process", "label": "Analysis"},
                {"type": "decision", "label": "Validation"},
                {"type": "process", "label": "Publication"},
                {"type": "start_end", "label": "Research End"}
            ]
            
            fig_result = await self.figure_generator.generate_flowchart({
                "action": "generate_flowchart",
                "title": f"Research Workflow - {metadata.title}",
                "caption": "Autonomous research workflow implemented in this study",
                "domain": metadata.domains[0] if metadata.domains else "general",
                "data": {
                    "steps": workflow_steps
                },
                "output_path": str(figures_dir)
            })
            
            if fig_result["success"]:
                figures.append({
                    "filename": fig_result["filename"],
                    "caption": fig_result["metadata"]["caption"],
                    "description": "Research workflow diagram showing the autonomous scientific discovery process.",
                    "type": "workflow_diagram"
                })
            
            logger.info(f"✅ Generated {len(figures)} figures for publication {metadata.pub_id}")
            return figures
            
        except BiologyError as e:
            logger.warning(f"⚠️ Could not generate figures: {e}")
            return []
    
    async def generate_journal_formatted_publication(self, request_data: GenerateJournalFormattedPublicationResult) -> GenerateJournalFormattedPublicationResult:
        """Generate publication formatted for a specific journal"""
        try:
            journal_name = request_data.get("journal", "nature")
            hypothesis_id = request_data.get("hypothesis_id")
            research_cycle_id = request_data.get("research_cycle_id")
            title = request_data.get("title")
            custom_content = request_data.get("custom_content", {})
            
            if not hypothesis_id and not title:
                return {
                    "success": False,
                    "error": "Either hypothesis_id or title must be provided"
                }
            
            # Generate publication ID
            pub_id = str(uuid.uuid4())[:8]
            
            # Gather content from various sources
            content_data = await self._gather_publication_content(
                hypothesis_id, research_cycle_id, custom_content
            )
            
            # Create metadata
            metadata = PublicationMetadata(
                pub_id=pub_id,
                title=title or content_data.get("title", f"Research Publication {pub_id}"),
                abstract=content_data.get("abstract", ""),
                domains=content_data.get("domains", []),
                keywords=content_data.get("keywords", []),
                hypothesis_id=hypothesis_id,
                research_cycle_id=research_cycle_id,
                consensus_score=content_data.get("consensus_score", 0.0)
            )
            
            # Generate content using templates
            content = await self._generate_imrad_content(metadata, content_data)
            
            # Create package structure
            package_path = self.packager.create_package_structure(pub_id)
            
            # Generate figures automatically
            figures = await self._generate_publication_figures(content_data, package_path, metadata)
            content.figures = figures
            
            # Format for specific journal
            journal_formatting = await self.journal_formatter.format_for_journal({
                "action": "format_for_journal",
                "journal": journal_name,
                "publication_content": {
                    "abstract": content.abstract,
                    "introduction": content.introduction,
                    "methods": content.methods,
                    "results": content.results,
                    "discussion": content.discussion,
                    "conclusions": content.conclusions,
                    "acknowledgments": "This research was conducted using the AXIOM META 4 autonomous scientific discovery platform.",
                    "author_contributions": "AXIOM Research Agent: Conceptualization, Methodology, Investigation, Writing - Original Draft, Writing - Review & Editing",
                    "data_availability": "All data and code are available through the AXIOM platform with DOI: " + (metadata.doi or "pending"),
                    "references": content.references
                },
                "metadata": {
                    "title": metadata.title,
                    "authors": metadata.authors,
                    "keywords": metadata.keywords,
                    "affiliations": ["AXIOM Research Platform"],
                    "corresponding_author": "AXIOM Research Agent",
                    "corresponding_email": "research@axiom.ai"
                }
            })
            
            if not journal_formatting["success"]:
                return {
                    "success": False,
                    "error": f"Journal formatting failed: {journal_formatting['error']}"
                }
            
            # Write journal-formatted content
            journal_formatted_content = journal_formatting["formatted_content"]
            (package_path / f"manuscript_{journal_name}.md").write_text(journal_formatted_content["manuscript"])
            
            # Write original content files
            await self._write_content_files(package_path, content, metadata)
            
            # Calculate package hash
            package_hash = self.packager.calculate_package_hash(package_path)
            
            # Generate DOI
            doi = DOIGenerator.generate_doi(package_hash)
            metadata.doi = doi
            
            # Blockchain validation
            integrity_proof = await self._create_integrity_proof(package_path, package_hash)
            metadata.blockchain_proof = integrity_proof.get("blockchain_proof")
            
            # Create final package
            package = PublicationPackage(
                metadata=metadata,
                content=content,
                package_path=package_path,
                package_hash=package_hash,
                integrity_proof=integrity_proof
            )
            
            # Write manifest and final files
            await self._finalize_package(package)
            
            logger.info(f"✅ Journal-formatted publication generated: {pub_id} for {journal_name} - DOI: {doi}")
            
            return {
                "success": True,
                "pub_id": pub_id,
                "doi": doi,
                "journal": journal_name,
                "package_path": str(package_path),
                "package_hash": package_hash,
                "title": metadata.title,
                "created_at": metadata.created_at.isoformat(),
                "integrity_proof": integrity_proof,
                "journal_formatting": {
                    "formatted_content": journal_formatted_content,
                    "warnings": journal_formatting["warnings"],
                    "errors": journal_formatting["errors"],
                    "word_counts": journal_formatting["word_counts"]
                }
            }
            
        except BiologyError as e:
            return self.handle_error(e, "generate_journal_formatted_publication")
    
    async def generate_publication_with_supplementary(self, request_data: GeneratePublicationWithSupplementaryResult) -> GeneratePublicationWithSupplementaryResult:
        """Generate publication with complete supplementary materials package"""
        try:
            journal_name = request_data.get("journal", "nature")
            hypothesis_id = request_data.get("hypothesis_id")
            research_cycle_id = request_data.get("research_cycle_id")
            title = request_data.get("title")
            custom_content = request_data.get("custom_content", {})
            supplementary_config = request_data.get("supplementary_config", {})
            
            if not hypothesis_id and not title:
                return {
                    "success": False,
                    "error": "Either hypothesis_id or title must be provided"
                }
            
            # Generate publication ID
            pub_id = str(uuid.uuid4())[:8]
            
            # Gather content from various sources
            content_data = await self._gather_publication_content(
                hypothesis_id, research_cycle_id, custom_content
            )
            
            # Create metadata
            metadata = PublicationMetadata(
                pub_id=pub_id,
                title=title or content_data.get("title", f"Research Publication {pub_id}"),
                abstract=content_data.get("abstract", ""),
                domains=content_data.get("domains", []),
                keywords=content_data.get("keywords", []),
                hypothesis_id=hypothesis_id,
                research_cycle_id=research_cycle_id,
                consensus_score=content_data.get("consensus_score", 0.0)
            )
            
            # Generate content using templates
            content = await self._generate_imrad_content(metadata, content_data)
            
            # Create package structure
            package_path = self.packager.create_package_structure(pub_id)
            
            # Generate figures automatically
            figures = await self._generate_publication_figures(content_data, package_path, metadata)
            content.figures = figures
            
            # Format for specific journal
            journal_formatting = await self.journal_formatter.format_for_journal({
                "action": "format_for_journal",
                "journal": journal_name,
                "publication_content": {
                    "abstract": content.abstract,
                    "introduction": content.introduction,
                    "methods": content.methods,
                    "results": content.results,
                    "discussion": content.discussion,
                    "conclusions": content.conclusions,
                    "acknowledgments": "This research was conducted using the AXIOM META 4 autonomous scientific discovery platform.",
                    "author_contributions": "AXIOM Research Agent: Conceptualization, Methodology, Investigation, Writing - Original Draft, Writing - Review & Editing",
                    "data_availability": "All data and code are available through the AXIOM platform with DOI: " + (metadata.doi or "pending"),
                    "references": content.references
                },
                "metadata": {
                    "title": metadata.title,
                    "authors": metadata.authors,
                    "keywords": metadata.keywords,
                    "affiliations": ["AXIOM Research Platform"],
                    "corresponding_author": "AXIOM Research Agent",
                    "corresponding_email": "research@axiom.ai"
                }
            })
            
            if not journal_formatting["success"]:
                return {
                    "success": False,
                    "error": f"Journal formatting failed: {journal_formatting['error']}"
                }
            
            # Generate supplementary materials
            supplementary_package = await self.supplementary_generator.generate_supplementary_package({
                "action": "generate_supplementary_package",
                "publication_id": pub_id,
                "materials_config": {
                    "include_extended_methods": supplementary_config.get("include_extended_methods", True),
                    "include_supplementary_data": supplementary_config.get("include_supplementary_data", True),
                    "include_protocols": supplementary_config.get("include_protocols", True),
                    "include_supplementary_figures": supplementary_config.get("include_supplementary_figures", True),
                    "include_supplementary_tables": supplementary_config.get("include_supplementary_tables", True),
                    "figures_count": supplementary_config.get("figures_count", 3),
                    "tables_count": supplementary_config.get("tables_count", 2)
                },
                "experimental_data": {
                    "overview": "Detailed experimental methods and protocols used in this autonomous research study.",
                    "protocols": [
                        {
                            "name": "Autonomous Hypothesis Generation Protocol",
                            "objective": "Generate scientifically sound hypotheses using AI",
                            "materials": ["Scientific literature database", "Machine learning models", "Validation algorithms"],
                            "procedure": ["Literature analysis", "Pattern recognition", "Hypothesis generation", "Validation"],
                            "expected_results": "Novel, testable scientific hypotheses",
                            "troubleshooting": [
                                {"problem": "Low hypothesis quality", "solution": "Improve training data quality"},
                                {"problem": "Validation failures", "solution": "Adjust validation criteria"}
                            ]
                        }
                    ],
                    "equipment": [
                        {
                            "name": "AXIOM Research Platform",
                            "type": "Autonomous Research System",
                            "manufacturer": "AXIOM Technologies",
                            "model": "META-4",
                            "settings": "Autonomous mode",
                            "calibration": "Continuous self-calibration"
                        }
                    ],
                    "reagents": [
                        {
                            "name": "Scientific Literature Data",
                            "cas_number": "N/A",
                            "purity": "Peer-reviewed sources",
                            "supplier": "Academic databases",
                            "storage": "Digital repositories",
                            "safety": "Standard data handling protocols"
                        }
                    ],
                    "data_analysis": "Advanced statistical analysis and machine learning methods",
                    "statistical_analysis": "Bayesian inference, cross-validation, and uncertainty quantification",
                    "quality_control": "Automated quality control with human oversight"
                },
                "data_sources": {
                    "description": "Raw data and supplementary datasets from autonomous research",
                    "format": "CSV, JSON, and other standard formats",
                    "access": "Available through AXIOM platform",
                    "datasets": [
                        {
                            "name": "Hypothesis Generation Dataset",
                            "type": "Research Data",
                            "size": "2.5 MB",
                            "format": "CSV",
                            "description": "Generated hypotheses and validation results",
                            "hash": "def456ghi789",
                            "access_url": f"https://axiom.ai/data/{pub_id}_hypotheses.csv"
                        }
                    ],
                    "processing_pipeline": "Automated data processing with quality control",
                    "validation_methods": "Cross-validation and statistical testing"
                },
                "protocol_data": {
                    "objective": "Detailed protocol for autonomous scientific research",
                    "materials": [
                        {"name": "Research Platform", "specifications": "AXIOM META-4"},
                        {"name": "Data Sources", "specifications": "Scientific literature"}
                    ],
                    "equipment": [
                        {"name": "Computing Infrastructure", "specifications": "High-performance computing"},
                        {"name": "Storage Systems", "specifications": "Distributed storage"}
                    ],
                    "procedure": [
                        {
                            "title": "Research Initialization",
                            "description": "Initialize autonomous research system",
                            "duration": "5 minutes",
                            "temperature": "Ambient",
                            "notes": "System self-check required"
                        }
                    ],
                    "troubleshooting": [
                        {
                            "problem": "System initialization failure",
                            "symptoms": "Error messages during startup",
                            "cause": "Configuration issues",
                            "solution": "Check configuration files",
                            "prevention": "Regular system maintenance"
                        }
                    ],
                    "notes": "This protocol enables fully autonomous scientific research",
                    "safety_information": "Standard computing safety protocols"
                },
                "figure_data": {
                    "figure_1": {
                        "title": "Research Workflow Overview",
                        "description": "Overview of the autonomous research workflow",
                        "data_source": "System logs and performance metrics",
                        "analysis_methods": "Workflow analysis",
                        "interpretation": "Demonstrates efficient autonomous research process"
                    },
                    "figure_2": {
                        "title": "Hypothesis Validation Results",
                        "description": "Validation results for generated hypotheses",
                        "data_source": "Validation experiments",
                        "analysis_methods": "Statistical validation",
                        "interpretation": "Shows high validation success rate"
                    },
                    "figure_3": {
                        "title": "Cross-Domain Performance",
                        "description": "Performance across different scientific domains",
                        "data_source": "Multi-domain experiments",
                        "analysis_methods": "Comparative analysis",
                        "interpretation": "Demonstrates broad applicability"
                    }
                },
                "table_data": {
                    "table_1": {
                        "title": "Experimental Results Summary",
                        "description": "Summary of experimental results",
                        "data_source": "Experimental data",
                        "statistical_methods": "Descriptive statistics",
                        "interpretation": "Key findings from experiments",
                        "table_data": "Results will be included in the table",
                        "notes": "All results validated through multiple methods"
                    },
                    "table_2": {
                        "title": "Performance Metrics",
                        "description": "Performance metrics for the research system",
                        "data_source": "System performance data",
                        "statistical_methods": "Performance analysis",
                        "interpretation": "System performance characteristics",
                        "table_data": "Metrics will be included in the table",
                        "notes": "Metrics collected over extended period"
                    }
                },
                "output_path": str(package_path / "supplementary")
            })
            
            if not supplementary_package["success"]:
                logger.warning(f"⚠️ Supplementary materials generation failed: {supplementary_package['error']}")
                supplementary_package = {"package_id": None, "total_materials": 0, "total_size": 0}
            
            # Write journal-formatted content
            journal_formatted_content = journal_formatting["formatted_content"]
            (package_path / f"manuscript_{journal_name}.md").write_text(journal_formatted_content["manuscript"])
            
            # Write original content files
            await self._write_content_files(package_path, content, metadata)
            
            # Calculate package hash
            package_hash = self.packager.calculate_package_hash(package_path)
            
            # Generate DOI
            doi = DOIGenerator.generate_doi(package_hash)
            metadata.doi = doi
            
            # Blockchain validation
            integrity_proof = await self._create_integrity_proof(package_path, package_hash)
            metadata.blockchain_proof = integrity_proof.get("blockchain_proof")
            
            # Create final package
            package = PublicationPackage(
                metadata=metadata,
                content=content,
                package_path=package_path,
                package_hash=package_hash,
                integrity_proof=integrity_proof
            )
            
            # Write manifest and final files
            await self._finalize_package(package)
            
            logger.info(f"✅ Complete publication with supplementary materials generated: {pub_id} for {journal_name} - DOI: {doi}")
            
            return {
                "success": True,
                "pub_id": pub_id,
                "doi": doi,
                "journal": journal_name,
                "package_path": str(package_path),
                "package_hash": package_hash,
                "title": metadata.title,
                "created_at": metadata.created_at.isoformat(),
                "integrity_proof": integrity_proof,
                "journal_formatting": {
                    "formatted_content": journal_formatted_content,
                    "warnings": journal_formatting["warnings"],
                    "errors": journal_formatting["errors"],
                    "word_counts": journal_formatting["word_counts"]
                },
                "supplementary_materials": {
                    "package_id": supplementary_package["package_id"],
                    "total_materials": supplementary_package["total_materials"],
                    "total_size": supplementary_package["total_size"],
                    "materials": supplementary_package.get("materials", [])
                }
            }
            
        except BiologyError as e:
            return self.handle_error(e, "generate_publication_with_supplementary")
