# Grafana configuration file for ATLAS Security Dashboard

[paths]
# Path to where Grafana stores its data
data = ./grafana/data
# Path to where Grafana stores its logs
logs = ./grafana/logs
# Path to where Grafana stores plugins
plugins = ./grafana/plugins
# Path to provisioning configuration files
provisioning = ./grafana/provisioning

[server]
# Protocol (http, https, h2, socket)
protocol = http
# The ip address to bind to, empty will bind to all interfaces
http_addr = 0.0.0.0
# The http port to use
http_port = 3000
# The public facing domain name used to access Grafana from a browser
domain = localhost
# Redirect to correct domain if host header does not match domain
enforce_domain = false
# The full public facing url
root_url = %(protocol)s://%(domain)s:%(http_port)s/
# Serve Grafana from subpath specified in `root_url` setting
serve_from_sub_path = false
# Log web requests
router_logging = false

[database]
# Either "mysql", "postgres" or "sqlite3", default is "sqlite3"
type = sqlite3
# For "sqlite3" only, path relative to data_path setting
path = grafana.db

[session]
# Either "memory", "file", "redis", "mysql", "postgres", default is "file"
provider = file
# Provider config options
provider_config = sessions

[analytics]
# Server reporting, sends usage counters to stats.grafana.org
reporting_enabled = false
# Google Analytics universal tracking code
google_analytics_ua_id =

[security]
# Default admin user, created on startup
admin_user = admin
# Default admin password, can be changed before first start of Grafana
admin_password = admin
# Used for signing
secret_key = SW2YcwTIb9zpOOhoPsMm
# Disable gravatar profile images
disable_gravatar = false
# Data source proxy whitelist (ip_or_domain:port separated by spaces)
data_source_proxy_whitelist =
# Disable protection against brute force login attempts
disable_brute_force_login_protection = false

[snapshots]
# Snapshot sharing options
external_enabled = false

[users]
# Disable user signup / registration
allow_sign_up = false
# Allow non admin users to create organizations
allow_org_create = false
# Set to true to automatically assign new users to the default organization (id 1)
auto_assign_org = true
# Set this value to automatically add new users to the provided organization (if auto_assign_org above is set to true)
auto_assign_org_id = 1
# Default role new users will be automatically assigned (if auto_assign_org above is set to true)
auto_assign_org_role = Viewer
# Background text for the user field on the login page
login_hint = email or username
# Default UI theme ("dark" or "light")
default_theme = dark

[auth]
# Set to true to disable (hide) the login form
disable_login_form = false
# Set to true to disable the signout link in the side menu
disable_signout_menu = false

[auth.anonymous]
# Enable anonymous access
enabled = false
# Specify organization name that should be used for unauthenticated users
org_name = Main Org.
# Specify role for unauthenticated users
org_role = Viewer

[auth.basic]
# Enable basic authentication
enabled = true

[log]
# Either "console", "file", "syslog". Default is console and file
mode = console file
# Either "debug", "info", "warn", "error", "critical", default is "info"
level = info

[log.console]
# Log line format, valid options are text, console and json
format = console
# For "console" mode only
level =

[log.file]
# Log line format, valid options are text, console and json
format = text
# This enables automated log rotate(switch of following options)
log_rotate = true
# Max line number of single file, default is 1000000
max_lines = 1000000
# Max size shift of single file, default is 28 means 1 << 28, 256MB
max_size_shift = 28
# Segment log daily, default is true
daily_rotate = true
# Expired days of log file(delete after max days), default is 7
max_days = 7

[metrics]
# Disable / Enable internal metrics
enabled = true
# Disable total stats (stat_totals_*) metrics to be generated
disable_total_stats = false

[grafana_com]
url = https://grafana.com

[alerting]
# Disable alerting engine & UI features
enabled = true
# Makes it possible to turn off alert rule execution but alerting UI is visible
execute_alerts = true

[explore]
# Enable the Explore section
enabled = true

[panels]
# If set to true Grafana will allow script tags in text panels
disable_sanitize_html = false
